initialize project

diff --git a/.sun-ci.yml b/.sun-ci.yml
--- a/.sun-ci.yml
+++ b/.sun-ci.yml
@@ -9,7 +9,11 @@ jobs:
     stage: ktlint
     image: amazoncorretto:17.0.10
     cache:
+<<<<<<< HEAD
       - key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
+=======
+      - key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}
+>>>>>>> c858e6c (initialize project)
         paths:
           - ./gradle
     before_script:
@@ -19,6 +23,7 @@ jobs:
     script:
       - ./gradlew ktlintCheck --daemon
       - status1=$?
+<<<<<<< HEAD
       - if [[ "$status1" = 0 ]] ; then
       - echo "*******************************************************"
       - echo "             Ktlint runs successfully                  " > .build_status
@@ -31,6 +36,20 @@ jobs:
       - echo "*******************************************************"
       - exit status1
       - fi
+=======
+      - if [[ "$status1" = 0 ]]; then
+        echo "*******************************************************"
+        echo "             Ktlint runs successfully                  " > .build_status
+        echo "                    (handshake)                        " > .build_icon
+        echo "*******************************************************"
+        else
+        echo "*******************************************************"
+        echo "                 Ktlint failed                         "
+        echo "     Please fix the reported issues before commit.     "
+        echo "*******************************************************"
+        exit $status1
+        fi
+>>>>>>> c858e6c (initialize project)
     only:
       branches:
         - develop
@@ -45,6 +64,7 @@ jobs:
     script:
       - ./gradlew detekt --daemon
       - status2=$?
+<<<<<<< HEAD
       - if [[ "$status2" = 0 ]] ; then
       - echo "*******************************************************"
       - echo "             Detekt runs successfully                  " > .build_status
@@ -57,6 +77,20 @@ jobs:
       - echo "*******************************************************"
       - exit status2
       - fi
+=======
+      - if [[ "$status2" = 0 ]]; then
+        echo "*******************************************************"
+        echo "             Detekt runs successfully                  " > .build_status
+        echo "                    (handshake)                        " > .build_icon
+        echo "*******************************************************"
+        else
+        echo "*******************************************************"
+        echo "                 Detekt failed                         "
+        echo "     Please fix the reported issues before commit.     "
+        echo "*******************************************************"
+        exit $status2
+        fi
+>>>>>>> c858e6c (initialize project)
     only:
       branches:
         - develop
